### ISSUE TITLE
Kinectic Branch?

### ISSUE THREAD

**Issue by aaravrav142** [rohbotics/xv_11_laser_driver#3]
Hi,
When will the ROS kinectic branch be launched on github. Any updates?

Thanks
Alex

**Comment by rohbotics** [comment]
The indigo branch should work just fine in kinetic. In general, a new branch for each distro is only done if necessary.

**Comment by jetdillo** [comment]
If you're compiling from source, the Indigo branch should compile fine. This code should be pretty stable by now. 
Maybe we could consider a kinetic branch for completeness sake ?

**Comment by rohbotics** [comment]
@jetdillo I made a `kinetic-devel` branch that has `firmware_version` defaulted to 2, as that is a common problem. I will run a binary release later this week, so the node should be available from debs next time there is a sync.

I will close this issue after I run the release.

@aaravrav142 Let me know if you have any issues.

**Comment by aaravrav142** [comment]
Hi, 

It compiles fine when source installed.  No issues. But a binary release version would be great.  I am an instructor and for students new to ROS sometimes source install is too much work and a binary release would ease that. Thanks for that. 

Alex

**Comment by rohbotics** [comment]
I ran a binary release job, but it won't be available until the next OSRF buildfarm sync in around 2 weeks.

**Comment by rohbotics** [comment]
Kinetic binaries are now available from packages.ros.org. Package sync email here: https://discourse.ros.org/t/new-packages-for-indigo-jade-and-kinetic-2017-04-03/1598

**Comment by AchmadFathoni** [comment]
@rohbotics How about melodic branch?

**Comment by rohbotics** [comment]
I ran a release job, should be available from apt-get a couple weeks after https://github.com/ros/rosdistro/pull/18097 is merged
