### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [rohbotics/xv_11_laser_driver#7]
Would you mind releasing this package also for the newest distribution ROS Noetic? :)

**Comment by rohbotics** [comment]
Can you make sure that the package compiles and runs under noetic?

If it does, I will do a release :)

**Comment by Timple** [comment]
I can verify that the package compiles. However I don't have the hardware at hand to validate...

Looking at the code I expect it to run as-is. So the options are: A) release and wait for bug-reports, B) wait until someone gets their hand on the hardware (can be a while in these strange times unfortunately).

**Comment by jetdillo** [comment]
I think I still have a Neato LIDAR rattling around in a box somewhere.
Compiling might suffice for a quick turn-around release though.
I suspect that most of the users of v_11_laser_driver are working with
legacy hardware where the firmware could be considered stable so chances
are if it worked over the past few releases, it's probably still working
today.
JMO,
'dillo

**Comment by rohbotics** [comment]
Ok I did the release, hopefully it all works as expected. 

https://github.com/rohbotics/rosdistro/pull/new/bloom-xv_11_laser_driver-3
